# release/mnt -> docker compose up -d
# local -> docker compose --env-file .env.dev -f compose.yaml -f compose-dev.yaml up -d

services:
  php:
    volumes:
      - ./src:/var/www/html/

  php-mnt:
    volumes:
      - ./src:/var/www/html/
